spring.datasource.url=jdbc:postgresql://localhost:5432/scanbite
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=dGhpcyBpcyBhIHZlcnkgc3Ryb25nIHNlY3JldCBrZXkgZm9yIHNjYW5iaXRlIGFwcGxpY2F0aW9u
jwt.expirationMs=3600000

# WebSocket
spring.websocket.path=/ws

server.port=8080
app.frontend.base-url=http://localhost:3001
